<footer>
    <div class="row">
        <div class="small-12 medium-12 large-4 columns">
            <h3>Abstract App</h3>
            <p>
                1015 Somewhere In<br/>
                Washington DC, 99999<br/>
                (999) 999-9999<br/>
                <a href="mailto:info@projectabstractcms.org">info@projectabstractcms.org</a>
            </p>
        </div>
        <div class="small-12 medium-12 large-4 columns">
            <h3>Quicklinks</h3>
            <p>
                <a href="#">Information &raquo;</a><br/>
                <a href="#">Portfolio &raquo;</a><br/>
                <a href="#">About Us &raquo;</a><br/>
                <a href="#">Services &raquo;</a><br/>
                <a href="#">Other Stuff &raquo;</a>
            </p>
        </div>
        <div class="small-12 medium-12 large-4 columns">
            <h3>More Information</h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque ornare ultrices.
                Aliquam sit amet tincidunt nisi. Sed justo ante, gravida et convallis id, dictum vel felis.
            </p>
        </div>
    </div>
</footer>