<div class="row home-content">
  <div class="small-12 medium-12 large-12 columns home-text">
    <p>
      <strong>Lorem ipsum dolor sit amet,</strong> consectetur adipiscing elit. Quisque vel ante ultrices, malesuada urna
      in, laoreet massa. In malesuada et nisl id laoreet. Nam malesuada ex ut dolor tincidunt, quis placerat nibh
      tincidunt. Suspendisse ut porttitor elit. Nullam sapien orci, sollicitudin quis metus eu, pellentesque vehicula
      sem. Sed vel vestibulum risus, et ornare neque. Pellentesque habitant morbi tristique senectus et netus et
      malesuada fames ac turpis
      egestas.
    </p>
  </div>
</div>

<div class="row callouts">
  <div class="small-12 medium-4 large-4 columns callout">
    <a href="#" class="callout-1">
      <img src="<?php echo template_file_static('images/blurry-night.jpg'); ?>" alt="Sample Callout For Something" />
      <h3>Sample Callout For Something</h3>
    </a>
  </div>
  <div class="small-12 medium-4 large-4 columns callout">
    <a href="#" class="callout-2">
      <img src="<?php echo template_file_static('images/coffee-beans.jpg'); ?>" alt="Another Callout For Something" />
      <h3>Another Callout For Something</h3>
    </a>
  </div>
  <div class="small-12 medium-4 large-4 columns callout">
    <a href="#" class="callout-3">
      <img src="<?php echo template_file_static('images/night-sky.jpg'); ?>" alt="This One Is Up To You" />
      <h3>This One Is Up To You</h3>
    </a>
  </div>
</div>

<script data-unload="1" type="text/javascript">
console.log('/templates/static/js/test.js UNLOAD call from script tag');
</script>

<script type="text/javascript">
$(document).ready(function() {
    console.log('/templates/static/js/test.js onload call from script tag');
});
</script>

<?php

$head = array(
    'title' => 'Abstract App Home',
    'meta' => array(
        'name' => array(
            'keywords' => array('content' => 'abstract application app home'),
            'description' => array('content' => 'Abstract App home page')
        )
    )
);
template_head_tags($head);

template_include( array(
    'css' => array(
        'css/test.css'
    ),
    'onload' => "",
    'unload' => ""
));

?>